# Generated by Django 5.0 on 2023-12-07 09:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите информацию о фурнитуре', max_length=100, verbose_name='Фурнитура')),
            ],
        ),
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите форму украшения', max_length=50, verbose_name='Форма украшения')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(help_text='Введите размер', validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(13)], verbose_name='Размер украшения')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите статус экземпляра украшения', max_length=20, verbose_name='Статус экземпляра украшения')),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название камня', max_length=200, verbose_name='Название камня')),
                ('description', models.TextField(help_text='Введите информацию о камне', verbose_name='Описание камня')),
                ('country', models.CharField(help_text='Информация о стране происхождения', max_length=100, verbose_name='Страна происхождения')),
                ('photo', models.ImageField(blank=True, help_text='Введите фото камня', null=True, upload_to='images', verbose_name='Фото камня')),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название украшения', max_length=200, verbose_name='Название украшения')),
                ('description', models.TextField(help_text='Введите описание украшения', max_length=500, verbose_name='Описание украшения')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену украшения', max_digits=7, verbose_name='Цена (руб.)')),
                ('photo', models.ImageField(help_text='Введите фото украшения', upload_to='images', verbose_name='Фото')),
                ('accessories', models.ForeignKey(help_text='Выберите фурнитуру', on_delete=django.db.models.deletion.CASCADE, to='catalog.accessories', verbose_name='Фурнитура украшения')),
                ('forma', models.ForeignKey(help_text='Введите форму украшения', on_delete=django.db.models.deletion.CASCADE, to='catalog.forma', verbose_name='Форма украшения')),
                ('size', models.ManyToManyField(help_text='Выберите размер(размеры)', to='catalog.size', verbose_name='Размер(размеры) украшения')),
                ('stone', models.ManyToManyField(help_text='Выберите камни', to='catalog.stone', verbose_name='Камни в украшении')),
            ],
        ),
        migrations.CreateModel(
            name='JewelryInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.CharField(help_text='Введите инвентарный номер экземпляра', max_length=20, null=True, verbose_name='Инвентарный номер')),
                ('due_back', models.DateField(blank=True, help_text='Введите конец срока статуса', null=True, verbose_name='Дата окончания срока статуса')),
                ('jewelry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.jewelry')),
                ('status', models.ForeignKey(help_text='Изменить состояние экземпляра', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Статус экземпляра украшения')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
