# Generated by Django 5.0 on 2023-12-07 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.IntegerField(help_text='Введите размер', validators=[django.core.validators.MaxValueValidator(65), django.core.validators.MinValueValidator(13)], verbose_name='Размер украшения'),
        ),
    ]
