# Generated by Django 5.0 on 2023-12-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='description',
            field=models.TextField(help_text='Введите описание украшения', max_length=1000, verbose_name='Описание украшения'),
        ),
    ]
