# Generated by Django 5.0 on 2023-12-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_jewelry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='size',
            field=models.ManyToManyField(help_text='Выберите размер(размеры)', null=True, to='catalog.size', verbose_name='Размер(размеры) украшения'),
        ),
    ]
