# Generated by Django 5.0 on 2023-12-07 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_jewelry_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.IntegerField(help_text='Введите размер', null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(10)], verbose_name='Размер украшения'),
        ),
    ]
